### ISSUE TITLE
光标的显示

### ISSUE THREAD

**Issue by NuonuoLabs** [maning0303/MNPasswordEditText#2]
请教下 我想显示光标可以怎么改？

**Comment by maning0303** [comment]
@1825492258 这个暂时没有光标显示，后期看把这个光标加上

**Comment by wmailn** [comment]
同问光标~

**Comment by maning0303** [comment]
@1825492258 @wmailn  最新版本光标已经支持，请查看最新版本，多谢反馈

**Comment by wmailn** [comment]
> @1825492258 @wmailn 最新版本光标已经支持，请查看最新版本，多谢反馈

3Q  还支持光标设置，给力
